abtNS = {}
local addon = abtNS
local strupper = strupper
local GetSpellInfo = GetSpellInfo

addon.battleshout = strupper(GetSpellInfo(2048) or '')  
addon.rend = strupper(GetSpellInfo(25208) or '') 
addon.judgement = strupper(GetSpellInfo(20271) or '')
addon.swp = strupper(GetSpellInfo(25368) or '')
addon.claw = strupper(GetSpellInfo(27000) or '')
addon.rake = strupper(GetSpellInfo(27003) or '')
addon.rip = strupper(GetSpellInfo(27008) or '')
addon.envenom = strupper(GetSpellInfo(32684) or '')
addon.ss = strupper(GetSpellInfo(26862) or '')
addon.snd = strupper(GetSpellInfo(6774) or '')
addon.evis = strupper(GetSpellInfo(26865) or '')
addon.shadowbolt = strupper(GetSpellInfo(27209) or '')
addon.shadowtrance = strupper(GetSpellInfo(17941) or '')
addon.huntersmark = strupper(GetSpellInfo(14325) or '')
addon.mendpet = strupper(GetSpellInfo(136) or '')
addon.lshield = strupper(GetSpellInfo(25472) or '') 
addon.fblast = strupper(GetSpellInfo(27079) or '')
addon.manatap = strupper(GetSpellInfo(28734) or '')
addon.rbandaged = strupper(GetSpellInfo(11196) or '')